name: Update next
on:
  workflow_run:
    workflows:
      - Release
    branches:
      - main
    types: completed
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rebase next to main
        run: |
          git fetch --unshallow
          git checkout next
          git rebase origin/main
          git push
